# Generated by Django 4.1.4 on 2023-11-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField(null=True)),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=50)),
                ('art_type', models.PositiveSmallIntegerField(choices=[(1, 'Painting'), (2, 'Photography'), (3, 'Sculpture')])),
                ('style', models.PositiveSmallIntegerField(choices=[(1, 'Cubism'), (2, 'Futurism'), (3, 'Dadaism'), (4, 'Surrealism'), (5, 'Pop Art'), (6, 'Street Art'), (7, 'Documentary'), (8, 'Modern'), (9, 'Abstractionism'), (10, 'Realism')])),
                ('info', models.TextField(null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatar/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='users/cv/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('date', models.CharField(max_length=100)),
                ('sales_value', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('material', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.artuser')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Individual'), (2, 'Group')])),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('organizer', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.artuser')),
            ],
        ),
    ]
