# Generated by Django 4.1.4 on 2023-11-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
